### PR TITLE
Add wallet client

### PR DESCRIPTION
**Pull request by cryptoMavrik**
Exposes the wagmi wallet client via hook.

### CODE REVIEW

**Review by frankfka — APPROVED** [review]
👍 For now we can duplicate this on the trade app for passing builds

**Comment by cryptoMavrik** [comment]
@frankfka should we add optional params to this that drill through jic?

**Comment by cryptoMavrik** [comment]
> @frankfka should we add optional params to this that drill through jic?

A lot of them are linked to the connector, but there are others that potentially could be useful (`batch`) though there aren't any current usecases.

**Comment by frankfka** [comment]
I think we add as we need, but i looked at this again, we should destructure `data` and only pass the wallet client through, otherwise a lot of other stuff from react query is exposed as well

**Comment by frankfka** [comment]
@cryptoMavrik gonna clean this up

**Pull request merged**
