### PR TITLE
Bump `ethers`

### PR DESCRIPTION
**Pull request by tmns**
Bumping `ethers` to correspond with changes in web [here](https://github.com/vertex-protocol/vertex-web-monorepo/pull/2369).

### CODE REVIEW

**Comment by frankfka** [comment]
Curious if you were able to:
- Run `lerna run build`
- Run some set of sanity tests in the SDK
- Locally bump `ethers` on the web repo and run the frontend locally on the new version

**Comment by tmns** [comment]
I was able to run the web upgrades branch linked locally with this one and didn't notice anything off.

Any specific sanity tests you want me to run?

**Comment by frankfka** [comment]
The client fullSanity e2e test should suffice

**Review by frankfka — APPROVED** [review]

**Comment by tmns** [comment]
Hmm those tests actually fail at the first order placement:

```
Minting tokens...
Approving allowance...
Depositing tokens with referral code...
Referral code
"-1"
Depositing tokens...
Placing order...
Error running test: EngineServerFailureError
    at EngineClient.checkServerStatus (vertex-typescript-sdk/packages/engine-client/dist/EngineBaseClient.ts:213:13)
    at EngineClient.execute (vertex-typescript-sdk/packages/engine-client/dist/EngineBaseClient.ts:149:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EngineClient.placeOrder (vertex-typescript-sdk/packages/engine-client/dist/EngineExecuteClient.ts:55:11)
    at async fullSanity (vertex-typescript-sdk/apps/e2e/src/client/fullSanity.ts:73:23) {
  responseData: {
    status: 'failure',
    signature: '0x0f149dc44d49934610078c344482d6f42503dbaaa7c7f05e33042724315f87a1636ce47bc171acaf0a80359c6d5efbd61bce75f0138d3e908fa754fd74e680f11c',
    error_code: 2008,
    error: 'The order cannot be placed as it is post-only and crosses the book. Please adjust your order parameters.',
    request_type: 'execute_place_order'
  }
}
```

But this also happens on `main` so it doesn't seem related to the version bump.

**Comment by frankfka** [comment]
Ah yeah, probs need to adjust the order prices in sanity to correspond to the latest mkt conditions.

If you got past the mint, deposit, and was able to generate signatures then we're gtg

**Pull request merged**
